[package]
name = "foldermanager-app"
version = "0.1.0"
edition = "2024"



[dependencies]
gtk4     = "0.10.2"
glib = "0.14"
gdk4 = "0.6"
walkdir = "2.3"
rayon = "1.7"
humansize = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"